let dbclient find itself when running in multihop mode

diff --git a/util/simple-test b/util/simple-test
--- a/util/simple-test
+++ b/util/simple-test
@@ -48,8 +48,10 @@ if ! [ "$recursive" ]; then
 	init_keys
 	"$D/dbclient" -t -i key -o UserKnownHostsFile=known_hosts \
 		-J "$D/dropbear -iF $log_opt -r key -A key.pub" \
-		localhost "$tmpdir/simple-test -r $log_opt $D $tmpdir"
-	exit
+		localhost exec "$tmpdir/simple-test -r $log_opt $D $tmpdir" ||
+	    status=$?
+	cat "$tmpdir/result" >&2
+	exit "$status"
 else
 	T=${2:-.}
 	cd "$T"
@@ -95,14 +97,16 @@ check(){ showcmd check "$@"; _check "$@"; }
 onexit(){
 	status=$?
 	trap : TERM; trap - EXIT; set +e
+	exec >$T/result
 	case $status:$failed in
 	0:0)	printf "\n$rev${green}EVERYTHING OK$norm\n";;
-	*)	printf >&2 "\n$rev${red}STATUS $status, FAILED $failed$norm\n"
-		exit 1
+	*)	printf "\n$rev${red}STATUS $status, FAILED $failed$norm\n"
+		status=1
 		;;
 	esac
 	kill -TERM -$$
 	wait
+	exit $status
 }
 trap onexit EXIT
 trap exit INT TERM
@@ -147,6 +151,9 @@ check ':foobar\n:0' \
 check '* 9999 2222\n:* 9999 * 2222\n:0' \
 	dssh $H$I -p "$port" -b 127.0.0.1:9999 127.0.0.1 \
 		'echo $SSH_CONNECTION; echo >&2 $SSH_CLIENT'
+check ':test\n:0' \
+	multi/dbclient $H$I -p 1 \
+		localhost/$port,localhost/$port,localhost/$port echo test
 
 v dssh $H$P$I \
 	-R 8888:localhost:$port \
@@ -173,14 +180,17 @@ hcheck % $H$I -p $local_port
 
 ##################################################################
 
+args="-i key -o UserKnownHostsFile=known_hosts -P $port local.txt localhost:$T/remote.txt"
 echo first > local.txt
-v "$D/dropbearmulti" scp -i key -o UserKnownHostsFile=known_hosts \
-	-P $port local.txt localhost:$T/remote.txt && :
+v "$D/dropbearmulti" scp $args && :
 check ::0 cmp local.txt remote.txt
 
 echo second > local.txt
-v multi/scp -i key -o UserKnownHostsFile=known_hosts \
-	-P $port local.txt localhost:$T/remote.txt && :
+v multi/scp $opts $args && :
+check ::0 cmp local.txt remote.txt
+
+echo third > local.txt
+v env PATH=multi scp $args && :
 check ::0 cmp local.txt remote.txt
 
 ##################################################################
